const gconstLabels = {
  'general': 'General',
  'gconst_default_game_timelimit': 'Timelimit',
  'gconst_expose_timers_to_lua': 'Expose Timers to Lua',
  'gconst_powerups_drop': 'Powerup Drop',
  'physics': 'physics',
  'gconst_player_isbullet': 'Player Hitbox',
  'gconst_double_jump_velocity': 'Double Jump Velocity',
  'gconst_jump_velocity': 'Jump Velocity',
  'gconst_playerinair_acceleration': 'Air Acceleration',
  'gconst_playerinair_aircontrol': 'Air Control',
  'gconst_playerinair_bunny_accelerate': 'Bunny Acceleration',
  'gconst_playerinair_bunny_wishspeed': 'Bunny Wishspeed',
  'gconst_playerinair_decceleration': 'Air Decceleration',
  'gconst_playerinaircrouched_acceleration': 'Crouched Air Acceleration',
  'gconst_playeronground_acceleration': 'Ground Acceleration',
  'gconst_playeronground_friction': 'Ground Friction',
  'gconst_playeronground_speed': 'Ground Speed',
  'gconst_playerongroundcrouched_speed': 'Crouched Ground Speed',
  'gconst_wallclipping': 'Wall Clipping',
  'gconst_world_gravity': 'Gravity',
  'sound': 'Sound',
  'gconst_armor100_faratten': 'Yellow Armor Sound Range',
  'gconst_armor150_faratten': 'Red Armor Sound Range',
  'gconst_armor50_faratten': 'Green Armor Sound Range',
  'gconst_mega_faratten': 'Mega Sound Range',
  'melee': 'Melee',
  'gconst_melee_damage': 'Melee Damage',
  'gconst_melee_knockmult': 'Melee Knockback Multiplier',
  'gconst_melee_knockmult_airbourne': 'Melee Air Knockback Multiplier',
  'gconst_melee_range': 'Melee Range',
  'gconst_melee_reload': 'Melee Reload Time',
  'gconst_melee_trace_radius': 'Melee Trace',
  'burstgun': 'Burst Gun',
  'gconst_burst_damage': 'Burst Gun Damage',
  'gconst_burst_knockmult': 'Burst Gun Knockback Multiplier',
  'gconst_burst_knockmult_airbourne': 'Burst Gun Air Knockback Multiplier',
  'gconst_burst_speed': 'Burst Gun Speed',
  'gconst_burstgun_ammopickupammo': 'Burst Gun Box Ammo',
  'gconst_burstgun_burstsegments': 'Burst Gun Burst Segments',
  'gconst_burstgun_lowammo': 'Burst Gun Low Ammo',
  'gconst_burstgun_maxammo': 'Burst Gun Max Ammo',
  'gconst_burstgun_reload': 'Burst Gun Reload Time',
  'gconst_burstgun_startammo': 'Burst Gun Start Ammo',
  'gconst_burstgun_weaponpickupammo': 'Burst Gun Weapon Ammo',
  'shotgun': 'Shotgun',
  'gconst_shotgun_pellet_damage': 'Shotgun Damage',
  'gconst_shotgun_pellet_knockmult': 'Shotgun Knockback Multiplier',
  'gconst_shotgun_pellet_knockmult_airbourne': 'Shotgun Air Knockback Multiplier',
  'gconst_shotgun_pellet_range': 'Shotgun Range',
  'gconst_shotgun_pellet_trace_radius_entities': 'Shotgun Entity Trace',
  'gconst_shotgun_pellet_trace_radius_world': 'Shotgun World Trace',
  'gconst_shotgun_ammopickupammo': 'Shotgun Box Ammo',
  'gconst_shotgun_lowammo': 'Shotgun Low Ammo',
  'gconst_shotgun_maxammo': 'Shotgun Max Ammo',
  'gconst_shotgun_reload': 'Shotgun Reload Time',
  'gconst_shotgun_weaponpickupammo': 'Shotgun Weapon Ammo',
  'grenadelauncher': 'Grenade Launcher',
  'gconst_grenade_damage': 'Grenade Launcher Damage',
  'gconst_grenade_damage_splashmult': 'Grenade Launcher Splash Damage Multiplier',
  'gconst_grenade_explosion_radius': 'Grenade Launcher Splash Radius',
  'gconst_grenade_gravity': 'Grenade Launcher Gravity',
  'gconst_grenade_speed_initial': 'Grenade Launcher Initial Speed',
  'gconst_grenade_trace_radius_entities': 'Grenade Launcher Entity Trace',
  'gconst_grenade_trace_radius_world': 'Grenade Launcher World Trace',
  'gconst_grenadelauncher_ammopickupammo': 'Grenade Launcher Box Ammo',
  'gconst_grenadelauncher_lowammo': 'Grenade Launcher Low Ammo',
  'gconst_grenadelauncher_maxammo': 'Grenade Launcher Max Ammo',
  'gconst_grenadelauncher_reload': 'Grenade Launcher Reload Time',
  'gconst_grenadelauncher_weaponpickupammo': 'Grenade Launcher Weapon Ammo',
  'plasmarifle': 'Plasma',
  'gconst_cell_damage': 'Plasma Damage',
  'gconst_cell_damage_splashmult': 'Plasma Splash Damage Multiplier',
  'gconst_cell_explosion_radius': 'Plasma Splash Radius',
  'gconst_cell_knockmult': 'Plasma Knockback Multiplier',
  'gconst_cell_knockmult_airbourne': 'Plasma Air Knockback Multiplier',
  'gconst_cell_knockmult_self': 'Plasma Self Knockback Multiplier',
  'gconst_cell_speed': 'Plasma Speed',
  'gconst_cell_trace_radius_entities': 'Plasma Entity Trace',
  'gconst_cell_trace_radius_world': 'Plasma World Trace',
  'gconst_plasmarifle_ammopickupammo': 'Plasma Box Ammo',
  'gconst_plasmarifle_lowammo': 'Plasma Low Ammo',
  'gconst_plasmarifle_maxammo': 'Plasma Max Ammo',
  'gconst_plasmarifle_reload': 'Plasma Reload Time',
  'gconst_plasmarifle_weaponpickupammo': 'Plasma Weapon Ammo',
  'rocketlauncher': 'Rocket Launcher',
  'gconst_rocket_damage': 'Rocket Launcher Damage',
  'gconst_rocket_damage_splashmult': 'Rocket Launcher Splash Damage Multiplier',
  'gconst_rocket_explosion_radius': 'Rocket Launcher Splash Radius',
  'gconst_rocket_knockmult': 'Rocket Launcher Knockback Multiplier',
  'gconst_rocket_knockmult_airbourne': 'Rocket Launcher Air Knockback Multiplier',
  'gconst_rocket_knockmult_self': 'Rocket Launcher Self Knockback Multiplier',
  'gconst_rocket_speed': 'Rocket Launcher Speed',
  'gconst_rocket_trace_radius_entities': 'Rocket Launcher Entity Trace',
  'gconst_rocket_trace_radius_world': 'Rocket Launcher World Trace',
  'gconst_rocketlauncher_ammopickupammo': 'Rocket Launcher Box Ammo',
  'gconst_rocketlauncher_lowammo': 'Rocket Launcher Low Ammo',
  'gconst_rocketlauncher_maxammo': 'Rocket Launcher Max Ammo',
  'gconst_rocketlauncher_reload': 'Rocket Launcher Reload Time',
  'gconst_rocketlauncher_weaponpickupammo': 'Rocket Launcher Weapon Ammo',
  'ioncannon': 'Ion Cannon',
  'gconst_beam_damage': 'Ion Cannon Damage',
  'gconst_beam_distance': 'Ion Cannon Distance',
  'gconst_beam_knockmult': 'Ion Cannon Knockback Multiplier',
  'gconst_beam_knockmult_airbourne': 'Ion Cannon Air Knockback Multiplier',
  'gconst_beam_trace_radius_entities': 'Ion Cannon Entity Trace',
  'gconst_beam_trace_radius_world': 'Ion Cannon World Trace',
  'gconst_ioncannon_ammopickupammo': 'Ion Cannon Box Ammo',
  'gconst_ioncannon_hum': 'Ion Cannon Hum',
  'gconst_ioncannon_hum_faratten': 'Ion Cannon Hum Sound Range',
  'gconst_ioncannon_lowammo': 'Ion Cannon Low Ammo',
  'gconst_ioncannon_maxammo': 'Ion Cannon Max Ammo',
  'gconst_ioncannon_reload': 'Ion Cannon Reload Time',
  'gconst_ioncannon_weaponpickupammo': 'Ion Cannon Weapon Ammo',
  'boltrifle': 'Bolt Rifle',
  'gconst_bolt_damage': 'Bolt Rifle Damage',
  'gconst_bolt_knockmult': 'Bolt Rifle Knockback Multiplier',
  'gconst_bolt_knockmult_airbourne': 'Bolt Rifle Air Knockback Multiplier',
  'gconst_bolt_range': 'Bolt Rifle Range',
  'gconst_bolt_trace_radius_entities': 'Bolt Rifle Entity Trace',
  'gconst_bolt_trace_radius_world': 'Bolt Rifle World Trace',
  'gconst_boltrifle_ammopickupammo': 'Bolt Rifle Box Ammo',
  'gconst_boltrifle_hum': 'Bolt Rifle Hum',
  'gconst_boltrifle_hum_faratten': 'Bolt Rifle Hum Sound Range',
  'gconst_boltrifle_lowammo': 'Bolt Rifle Low Ammo',
  'gconst_boltrifle_maxammo': 'Bolt Rifle Max Ammo',
  'gconst_boltrifle_reload': 'Bolt Rifle Reload Time',
  'gconst_boltrifle_weaponpickupammo': 'Bolt Rifle Weapon Ammo',
  'stake': 'Stake Launcher',
  'gconst_stake_damage': 'Stake Launcher Damage',
  'gconst_stake_gravity': 'Stake Launcher Gravity',
  'gconst_stake_knockmult': 'Stake Launcher Knockback Multiplier',
  'gconst_stake_knockmult_airbourne': 'Stake Launcher Air Knockback Multiplier',
  'gconst_stake_radius': 'Stake Launcher Radius',
  'gconst_stake_speed': 'Stake Launcher Speed',
  'gconst_stake_trace_radius': 'Stake Launcher Trace',
  'gconst_stakelauncher_ammopickupammo': 'Stake Launcher Box Ammo',
  'gconst_stakelauncher_enabled': 'Stake Launcher Enabled',
  'gconst_stakelauncher_lowammo': 'Stake Launcher Low Ammo',
  'gconst_stakelauncher_maxammo': 'Stake Launcher Max Ammo',
  'gconst_stakelauncher_reload': 'Stake Launcher Reload Time',
  'gconst_stakelauncher_weaponpickupammo': 'Stake Launcher Weapon Ammo'
};