const gconstGroups = [
  {
    'name': 'general',
    'variables': [
      'gconst_default_game_timelimit',
      'gconst_expose_timers_to_lua',
      'gconst_powerups_drop',
    ]
  },
  {
    'name': 'physics',
    'variables': [
      'gconst_player_isbullet',
      'gconst_double_jump_velocity',
      'gconst_jump_velocity',
      'gconst_playerinair_acceleration',
      'gconst_playerinair_aircontrol',
      'gconst_playerinair_bunny_accelerate',
      'gconst_playerinair_bunny_wishspeed',
      'gconst_playerinair_decceleration',
      'gconst_playerinaircrouched_acceleration',
      'gconst_playeronground_acceleration',
      'gconst_playeronground_friction',
      'gconst_playeronground_speed',
      'gconst_playerongroundcrouched_speed',
      'gconst_wallclipping',
      'gconst_world_gravity'
    ]
  },
  {
    'name': 'sound',
    'variables': [
      'gconst_armor100_faratten',
      'gconst_armor150_faratten',
      'gconst_armor50_faratten',
      'gconst_mega_faratten'
    ]
  },
  {
    'name': 'melee',
    'damage': 'gconst_melee_damage',
    'reload': 'gconst_melee_reload',
    'variables': [
      'gconst_melee_damage',
      'gconst_melee_knockmult',
      'gconst_melee_knockmult_airbourne',
      'gconst_melee_range',
      'gconst_melee_reload',
      'gconst_melee_trace_radius'
    ]
  },
  {
    'name': 'burstgun',
    'damage': 'gconst_burst_damage',
    'reload': 'gconst_burstgun_reload',
    'variables': [
      'gconst_burst_damage',
      'gconst_burst_knockmult',
      'gconst_burst_knockmult_airbourne',
      'gconst_burst_speed',
      'gconst_burstgun_ammopickupammo',
      'gconst_burstgun_burstsegments',
      'gconst_burstgun_lowammo',
      'gconst_burstgun_maxammo',
      'gconst_burstgun_reload',
      'gconst_burstgun_startammo',
      'gconst_burstgun_weaponpickupammo'
    ]
  },
  {
    'name': 'shotgun',
    'damage': 'gconst_shotgun_pellet_damage',
    'reload': 'gconst_shotgun_reload',
    'variables': [
      'gconst_shotgun_pellet_damage',
      'gconst_shotgun_pellet_knockmult',
      'gconst_shotgun_pellet_knockmult_airbourne',
      'gconst_shotgun_pellet_range',
      'gconst_shotgun_pellet_trace_radius_entities',
      'gconst_shotgun_pellet_trace_radius_world',
      'gconst_shotgun_ammopickupammo',
      'gconst_shotgun_lowammo',
      'gconst_shotgun_maxammo',
      'gconst_shotgun_reload',
      'gconst_shotgun_weaponpickupammo'
    ]
  },
  {
    'name': 'grenadelauncher',
    'damage': 'gconst_grenade_damage',
    'reload': 'gconst_grenadelauncher_reload',
    'variables': [
      'gconst_grenade_damage',
      'gconst_grenade_damage_splashmult',
      'gconst_grenade_explosion_radius',
      'gconst_grenade_gravity',
      'gconst_grenade_speed_initial',
      'gconst_grenade_trace_radius_entities',
      'gconst_grenade_trace_radius_world',
      'gconst_grenadelauncher_ammopickupammo',
      'gconst_grenadelauncher_lowammo',
      'gconst_grenadelauncher_maxammo',
      'gconst_grenadelauncher_reload',
      'gconst_grenadelauncher_weaponpickupammo'
    ]
  },
  {
    'name': 'plasmarifle',
    'damage': 'gconst_cell_damage',
    'reload': 'gconst_plasmarifle_reload',
    'variables': [
      'gconst_cell_damage',
      'gconst_cell_damage_splashmult',
      'gconst_cell_explosion_radius',
      'gconst_cell_knockmult',
      'gconst_cell_knockmult_airbourne',
      'gconst_cell_knockmult_self',
      'gconst_cell_speed',
      'gconst_cell_trace_radius_entities',
      'gconst_cell_trace_radius_world',
      'gconst_plasmarifle_ammopickupammo',
      'gconst_plasmarifle_lowammo',
      'gconst_plasmarifle_maxammo',
      'gconst_plasmarifle_reload',
      'gconst_plasmarifle_weaponpickupammo'
    ]
  },
  {
    'name': 'rocketlauncher',
    'damage': 'gconst_rocket_damage',
    'reload': 'gconst_rocketlauncher_reload',
    'variables': [
      'gconst_rocket_damage',
      'gconst_rocket_damage_splashmult',
      'gconst_rocket_explosion_radius',
      'gconst_rocket_knockmult',
      'gconst_rocket_knockmult_airbourne',
      'gconst_rocket_knockmult_self',
      'gconst_rocket_speed',
      'gconst_rocket_trace_radius_entities',
      'gconst_rocket_trace_radius_world',
      'gconst_rocketlauncher_ammopickupammo',
      'gconst_rocketlauncher_lowammo',
      'gconst_rocketlauncher_maxammo',
      'gconst_rocketlauncher_reload',
      'gconst_rocketlauncher_weaponpickupammo'
    ]
  },
  {
    'name': 'ioncannon',
    'damage': 'gconst_beam_damage',
    'reload': 'gconst_ioncannon_reload',
    'variables': [
      'gconst_beam_damage',
      'gconst_beam_distance',
      'gconst_beam_knockmult',
      'gconst_beam_knockmult_airbourne',
      'gconst_beam_trace_radius_entities',
      'gconst_beam_trace_radius_world',
      'gconst_ioncannon_ammopickupammo',
      'gconst_ioncannon_hum',
      'gconst_ioncannon_hum_faratten',
      'gconst_ioncannon_lowammo',
      'gconst_ioncannon_maxammo',
      'gconst_ioncannon_reload',
      'gconst_ioncannon_weaponpickupammo'
    ]
  },
  {
    'name': 'boltrifle',
    'damage': 'gconst_bolt_damage',
    'reload': 'gconst_boltrifle_reload',
    'variables': [
      'gconst_bolt_damage',
      'gconst_bolt_knockmult',
      'gconst_bolt_knockmult_airbourne',
      'gconst_bolt_range',
      'gconst_bolt_trace_radius_entities',
      'gconst_bolt_trace_radius_world',
      'gconst_boltrifle_ammopickupammo',
      'gconst_boltrifle_hum',
      'gconst_boltrifle_hum_faratten',
      'gconst_boltrifle_lowammo',
      'gconst_boltrifle_maxammo',
      'gconst_boltrifle_reload',
      'gconst_boltrifle_weaponpickupammo'
    ]
  },
  {
    'name': 'stake',
    'damage': 'gconst_stake_damage',
    'reload': 'gconst_stakelauncher_reload',
    'variables': [
      'gconst_stake_damage',
      'gconst_stake_gravity',
      'gconst_stake_knockmult',
      'gconst_stake_knockmult_airbourne',
      'gconst_stake_radius',
      'gconst_stake_speed',
      'gconst_stake_trace_radius',
      'gconst_stakelauncher_ammopickupammo',
      'gconst_stakelauncher_enabled',
      'gconst_stakelauncher_lowammo',
      'gconst_stakelauncher_maxammo',
      'gconst_stakelauncher_reload',
      'gconst_stakelauncher_weaponpickupammo'
    ]
  }
];

const rulesetDefault = {
  'gconst_default_game_timelimit': '10',
  'gconst_expose_timers_to_lua': '0',
  'gconst_powerups_drop': '1',
  'gconst_player_isbullet': '1',
  'gconst_double_jump_velocity': '105',
  'gconst_jump_velocity': '255',
  'gconst_playerinair_acceleration': '0.95',
  'gconst_playerinair_aircontrol': '150',
  'gconst_playerinair_bunny_accelerate': '60',
  'gconst_playerinair_bunny_wishspeed': '30',
  'gconst_playerinair_decceleration': '2.5',
  'gconst_playerinaircrouched_acceleration': '0.475',
  'gconst_playeronground_acceleration': '4000',
  'gconst_playeronground_friction': '6',
  'gconst_playeronground_speed': '320',
  'gconst_playerongroundcrouched_speed': '120',
  'gconst_wallclipping': '1',
  'gconst_world_gravity': '750',
  'gconst_armor100_faratten': '2200',
  'gconst_armor150_faratten': '2200',
  'gconst_armor50_faratten': '2200',
  'gconst_mega_faratten': '2200',
  'gconst_melee_damage': '80',
  'gconst_melee_knockmult': '1.57',
  'gconst_melee_knockmult_airbourne': '0.94',
  'gconst_melee_range': '68',
  'gconst_melee_reload': '800',
  'gconst_melee_trace_radius': '10',
  'gconst_burst_damage': '6',
  'gconst_burst_knockmult': '1.25',
  'gconst_burst_knockmult_airbourne': '1.5',
  'gconst_burst_speed': '4000',
  'gconst_burstgun_ammopickupammo': '10',
  'gconst_burstgun_burstsegments': '6',
  'gconst_burstgun_lowammo': '5',
  'gconst_burstgun_maxammo': '20',
  'gconst_burstgun_reload': '450',
  'gconst_burstgun_startammo': '10',
  'gconst_burstgun_weaponpickupammo': '10',
  'gconst_shotgun_pellet_damage': '5',
  'gconst_shotgun_pellet_knockmult': '1.6',
  'gconst_shotgun_pellet_knockmult_airbourne': '1.4',
  'gconst_shotgun_pellet_range': '4096',
  'gconst_shotgun_pellet_trace_radius_entities': '0.75',
  'gconst_shotgun_pellet_trace_radius_world': '0.75',
  'gconst_shotgun_ammopickupammo': '6',
  'gconst_shotgun_lowammo': '3',
  'gconst_shotgun_maxammo': '12',
  'gconst_shotgun_reload': '900',
  'gconst_shotgun_weaponpickupammo': '6',
  'gconst_grenade_damage': '100',
  'gconst_grenade_damage_splashmult': '0.85',
  'gconst_grenade_explosion_radius': '180',
  'gconst_grenade_gravity': '700',
  'gconst_grenade_speed_initial': '700',
  'gconst_grenade_trace_radius_entities': '2',
  'gconst_grenade_trace_radius_world': '2',
  'gconst_grenadelauncher_ammopickupammo': '5',
  'gconst_grenadelauncher_lowammo': '2',
  'gconst_grenadelauncher_maxammo': '10',
  'gconst_grenadelauncher_reload': '800',
  'gconst_grenadelauncher_weaponpickupammo': '5',
  'gconst_cell_damage': '16',
  'gconst_cell_damage_splashmult': '1',
  'gconst_cell_explosion_radius': '32',
  'gconst_cell_knockmult': '0.85',
  'gconst_cell_knockmult_airbourne': '1',
  'gconst_cell_knockmult_self': '2',
  'gconst_cell_speed': '2000',
  'gconst_cell_trace_radius_entities': '2.5',
  'gconst_cell_trace_radius_world': '2.5',
  'gconst_plasmarifle_ammopickupammo': '50',
  'gconst_plasmarifle_lowammo': '25',
  'gconst_plasmarifle_maxammo': '100',
  'gconst_plasmarifle_reload': '100',
  'gconst_plasmarifle_weaponpickupammo': '50',
  'gconst_rocket_damage': '100',
  'gconst_rocket_damage_splashmult': '0.85',
  'gconst_rocket_explosion_radius': '120',
  'gconst_rocket_knockmult': '0.85',
  'gconst_rocket_knockmult_airbourne': '1',
  'gconst_rocket_knockmult_self': '1.12',
  'gconst_rocket_speed': '1000',
  'gconst_rocket_trace_radius_entities': '1.25',
  'gconst_rocket_trace_radius_world': '1.25',
  'gconst_rocketlauncher_ammopickupammo': '8',
  'gconst_rocketlauncher_lowammo': '4',
  'gconst_rocketlauncher_maxammo': '16',
  'gconst_rocketlauncher_reload': '800',
  'gconst_rocketlauncher_weaponpickupammo': '8',
  'gconst_beam_damage': '6',
  'gconst_beam_distance': '768',
  'gconst_beam_knockmult': '1.6',
  'gconst_beam_knockmult_airbourne': '1.6',
  'gconst_beam_trace_radius_entities': '0.75',
  'gconst_beam_trace_radius_world': '0.75',
  'gconst_ioncannon_ammopickupammo': '75',
  'gconst_ioncannon_hum': '1',
  'gconst_ioncannon_hum_faratten': '1250',
  'gconst_ioncannon_lowammo': '35',
  'gconst_ioncannon_maxammo': '150',
  'gconst_ioncannon_reload': '44',
  'gconst_ioncannon_weaponpickupammo': '75',
  'gconst_bolt_damage': '80',
  'gconst_bolt_knockmult': '0.5',
  'gconst_bolt_knockmult_airbourne': '0.5',
  'gconst_bolt_range': '16384',
  'gconst_bolt_trace_radius_entities': '0.75',
  'gconst_bolt_trace_radius_world': '0.75',
  'gconst_boltrifle_ammopickupammo': '5',
  'gconst_boltrifle_hum': '1',
  'gconst_boltrifle_hum_faratten': '1500',
  'gconst_boltrifle_lowammo': '2',
  'gconst_boltrifle_maxammo': '10',
  'gconst_boltrifle_reload': '1375',
  'gconst_boltrifle_weaponpickupammo': '5',
  'gconst_stake_damage': '100',
  'gconst_stake_gravity': '700',
  'gconst_stake_knockmult': '1',
  'gconst_stake_knockmult_airbourne': '1',
  'gconst_stake_radius': '2',
  'gconst_stake_speed': '3500',
  'gconst_stake_trace_radius': '1',
  'gconst_stakelauncher_ammopickupammo': '5',
  'gconst_stakelauncher_enabled': '0',
  'gconst_stakelauncher_lowammo': '5',
  'gconst_stakelauncher_maxammo': '20',
  'gconst_stakelauncher_reload': '1250',
  'gconst_stakelauncher_weaponpickupammo': '10'
};

const clearNames = {
  'general': 'General',
  'gconst_default_game_timelimit': 'Timelimit',
  'gconst_expose_timers_to_lua': 'Expose timers to Lua',
  'gconst_powerups_drop': 'Powerup drop',
  'physics': 'physics',
  'gconst_player_isbullet': 'Player Hitbox',
  'gconst_double_jump_velocity': 'Double Jump Velocity',
  'gconst_jump_velocity': 'Jump Velocity',
  'gconst_playerinair_acceleration': 'Air Acceleration',
  'gconst_playerinair_aircontrol': 'Air Control',
  'gconst_playerinair_bunny_accelerate': 'Bunny Acceleration',
  'gconst_playerinair_bunny_wishspeed': 'Bunny Wishspeed',
  'gconst_playerinair_decceleration': 'Air Decceleration',
  'gconst_playerinaircrouched_acceleration': 'Crouched Air Acceleration',
  'gconst_playeronground_acceleration': 'Ground Acceleration',
  'gconst_playeronground_friction': 'Ground Friction',
  'gconst_playeronground_speed': 'Ground Speed',
  'gconst_playerongroundcrouched_speed': 'Crouched Ground Speed',
  'gconst_wallclipping': 'Wall Clipping',
  'gconst_world_gravity': 'Gravity',
  'sound': 'Sound',
  'gconst_armor100_faratten': 'Yellow Armor Sound Range',
  'gconst_armor150_faratten': 'Red Armor Sound Range',
  'gconst_armor50_faratten': 'Green Armor Sound Range',
  'gconst_mega_faratten': 'Mega Sound Range',
  'melee': 'Melee',
  'gconst_melee_damage': 'Melee Damage',
  'gconst_melee_knockmult': 'Melee Knockback Multiplier',
  'gconst_melee_knockmult_airbourne': 'Melee Air Knockback Multiplier',
  'gconst_melee_range': 'Melee Range',
  'gconst_melee_reload': 'Melee Reload Time',
  'gconst_melee_trace_radius': 'Melee Trace',
  'burstgun': 'Burst Gun',
  'gconst_burst_damage': 'Burst Gun Damage',
  'gconst_burst_knockmult': 'Burst Gun Knockback Multiplier',
  'gconst_burst_knockmult_airbourne': 'Burst Gun Air Knockback Multiplier',
  'gconst_burst_speed': 'Burst Gun Speed',
  'gconst_burstgun_ammopickupammo': 'Burst Gun Box Ammo',
  'gconst_burstgun_burstsegments': 'Burst Gun Burst Segments',
  'gconst_burstgun_lowammo': 'Burst Gun Low Ammo',
  'gconst_burstgun_maxammo': 'Burst Gun Max Ammo',
  'gconst_burstgun_reload': 'Burst Gun Reload Time',
  'gconst_burstgun_startammo': 'Burst Gun Start Ammo',
  'gconst_burstgun_weaponpickupammo': 'Burst Gun Weapon Ammo',
  'shotgun': 'Shotgun',
  'gconst_shotgun_pellet_damage': 'Shotgun Damage',
  'gconst_shotgun_pellet_knockmult': 'Shotgun Knockback Multiplier',
  'gconst_shotgun_pellet_knockmult_airbourne': 'Shotgun Air Knockback Multiplier',
  'gconst_shotgun_pellet_range': 'Shotgun Range',
  'gconst_shotgun_pellet_trace_radius_entities': 'Shotgun Entity Trace',
  'gconst_shotgun_pellet_trace_radius_world': 'Shotgun World Trace',
  'gconst_shotgun_ammopickupammo': 'Shotgun Box Ammo',
  'gconst_shotgun_lowammo': 'Shotgun Low Ammo',
  'gconst_shotgun_maxammo': 'Shotgun Max Ammo',
  'gconst_shotgun_reload': 'Shotgun Reload Time',
  'gconst_shotgun_weaponpickupammo': 'Shotgun Weapon Ammo',
  'grenadelauncher': 'Grenade Launcher',
  'gconst_grenade_damage': 'Grenade Launcher Damage',
  'gconst_grenade_damage_splashmult': 'Grenade Launcher Splash Damage Multiplier',
  'gconst_grenade_explosion_radius': 'Grenade Launcher Splash Radius',
  'gconst_grenade_gravity': 'Grenade Launcher Gravity',
  'gconst_grenade_speed_initial': 'Grenade Launcher Initial Speed',
  'gconst_grenade_trace_radius_entities': 'Grenade Launcher Entity Trace',
  'gconst_grenade_trace_radius_world': 'Grenade Launcher World Trace',
  'gconst_grenadelauncher_ammopickupammo': 'Grenade Launcher Box Ammo',
  'gconst_grenadelauncher_lowammo': 'Grenade Launcher Low Ammo',
  'gconst_grenadelauncher_maxammo': 'Grenade Launcher Max Ammo',
  'gconst_grenadelauncher_reload': 'Grenade Launcher Reload Time',
  'gconst_grenadelauncher_weaponpickupammo': 'Grenade Launcher Weapon Ammo',
  'plasmarifle': 'Plasma',
  'gconst_cell_damage': 'Plasma Damage',
  'gconst_cell_damage_splashmult': 'Plasma Splash Damage Multiplier',
  'gconst_cell_explosion_radius': 'Plasma Splash Radius',
  'gconst_cell_knockmult': 'Plasma Knockback Multiplier',
  'gconst_cell_knockmult_airbourne': 'Plasma Air Knockback Multiplier',
  'gconst_cell_knockmult_self': 'Plasma Self Knockback Multiplier',
  'gconst_cell_speed': 'Plasma Speed',
  'gconst_cell_trace_radius_entities': 'Plasma Entity Trace',
  'gconst_cell_trace_radius_world': 'Plasma World Trace',
  'gconst_plasmarifle_ammopickupammo': 'Plasma Box Ammo',
  'gconst_plasmarifle_lowammo': 'Plasma Low Ammo',
  'gconst_plasmarifle_maxammo': 'Plasma Max Ammo',
  'gconst_plasmarifle_reload': 'Plasma Reload Time',
  'gconst_plasmarifle_weaponpickupammo': 'Plasma Weapon Ammo',
  'rocketlauncher': 'Rocket Launcher',
  'gconst_rocket_damage': 'Rocket Launcher Damage',
  'gconst_rocket_damage_splashmult': 'Rocket Launcher Splash Damage Multiplier',
  'gconst_rocket_explosion_radius': 'Rocket Launcher Splash Radius',
  'gconst_rocket_knockmult': 'Rocket Launcher Knockback Multiplier',
  'gconst_rocket_knockmult_airbourne': 'Rocket Launcher Air Knockback Multiplier',
  'gconst_rocket_knockmult_self': 'Rocket Launcher Self Knockback Multiplier',
  'gconst_rocket_speed': 'Rocket Launcher Speed',
  'gconst_rocket_trace_radius_entities': 'Rocket Launcher Entity Trace',
  'gconst_rocket_trace_radius_world': 'Rocket Launcher World Trace',
  'gconst_rocketlauncher_ammopickupammo': 'Rocket Launcher Box Ammo',
  'gconst_rocketlauncher_lowammo': 'Rocket Launcher Low Ammo',
  'gconst_rocketlauncher_maxammo': 'Rocket Launcher Max Ammo',
  'gconst_rocketlauncher_reload': 'Rocket Launcher Reload Time',
  'gconst_rocketlauncher_weaponpickupammo': 'Rocket Launcher Weapon Ammo',
  'ioncannon': 'Ion Cannon',
  'gconst_beam_damage': 'Ion Cannon Damage',
  'gconst_beam_distance': 'Ion Cannon Distance',
  'gconst_beam_knockmult': 'Ion Cannon Knockback Multiplier',
  'gconst_beam_knockmult_airbourne': 'Ion Cannon Air Knockback Multiplier',
  'gconst_beam_trace_radius_entities': 'Ion Cannon Entity Trace',
  'gconst_beam_trace_radius_world': 'Ion Cannon World Trace',
  'gconst_ioncannon_ammopickupammo': 'Ion Cannon Box Ammo',
  'gconst_ioncannon_hum': 'Ion Cannon Hum',
  'gconst_ioncannon_hum_faratten': 'Ion Cannon Hum Sound Range',
  'gconst_ioncannon_lowammo': 'Ion Cannon Low Ammo',
  'gconst_ioncannon_maxammo': 'Ion Cannon Max Ammo',
  'gconst_ioncannon_reload': 'Ion Cannon Reload Time',
  'gconst_ioncannon_weaponpickupammo': 'Ion Cannon Weapon Ammo',
  'boltrifle': 'Bolt Rifle',
  'gconst_bolt_damage': 'Bolt Rifle Damage',
  'gconst_bolt_knockmult': 'Bolt Rifle Knockback Multiplier',
  'gconst_bolt_knockmult_airbourne': 'Bolt Rifle Air Knockback Multiplier',
  'gconst_bolt_range': 'Bolt Rifle Range',
  'gconst_bolt_trace_radius_entities': 'Bolt Rifle Entity Trace',
  'gconst_bolt_trace_radius_world': 'Bolt Rifle World Trace',
  'gconst_boltrifle_ammopickupammo': 'Bolt Rifle Box Ammo',
  'gconst_boltrifle_hum': 'Bolt Rifle Hum',
  'gconst_boltrifle_hum_faratten': 'Bolt Rifle Hum Sound Range',
  'gconst_boltrifle_lowammo': 'Bolt Rifle Low Ammo',
  'gconst_boltrifle_maxammo': 'Bolt Rifle Max Ammo',
  'gconst_boltrifle_reload': 'Bolt Rifle Reload Time',
  'gconst_boltrifle_weaponpickupammo': 'Bolt Rifle Weapon Ammo',
  'stake': 'Stake Launcher',
  'gconst_stake_damage': 'Stake Launcher Damage',
  'gconst_stake_gravity': 'Stake Launcher Gravity',
  'gconst_stake_knockmult': 'Stake Launcher Knockback Multiplier',
  'gconst_stake_knockmult_airbourne': 'Stake Launcher Air Knockback Multiplier',
  'gconst_stake_radius': 'Stake Launcher Radius',
  'gconst_stake_speed': 'Stake Launcher Speed',
  'gconst_stake_trace_radius': 'Stake Launcher Trace',
  'gconst_stakelauncher_ammopickupammo': 'Stake Launcher Box Ammo',
  'gconst_stakelauncher_enabled': 'Stake Launcher Enabled',
  'gconst_stakelauncher_lowammo': 'Stake Launcher Low Ammo',
  'gconst_stakelauncher_maxammo': 'Stake Launcher Max Ammo',
  'gconst_stakelauncher_reload': 'Stake Launcher Reload Time',
  'gconst_stakelauncher_weaponpickupammo': 'Stake Launcher Weapon Ammo'
};